<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AuditWorkbench.Web</RootNamespace>
    <AssemblyName>AuditWorkbench</AssemblyName>
    <UserSecretsId>audit-workbench-local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuditWorkbench.Application\AuditWorkbench.Application.csproj" />
  </ItemGroup>

</Project>
